// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadConfigFile() {
  return window['go']['main']['App']['LoadConfigFile']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveConfigFileAs(arg1) {
  return window['go']['main']['App']['SaveConfigFileAs'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
