// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<config.ClientConfig>;

export function GetStatus():Promise<main.StatusUpdate>;

export function LoadConfigFile():Promise<config.ClientConfig>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:config.ClientConfig):Promise<void>;

export function SaveConfigFileAs(arg1:config.ClientConfig):Promise<void>;

export function ShowWindow():Promise<void>;
